apiVersion: v1
kind: Service
metadata:
  name: chiquita
  labels:
    app: chiquita
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: chiquita